[package]
name = "mcp-error"
version = "0.3.1"
authors = ["vincent@ephais.eu"]
edition = "2021"
description = "Error management library for all the MCP Studio rust project"
license = "For the exclusive use of Ephais. Reserved Rights."

[dependencies]
