[package]
name = "ephais-error"
version = "0.1.2"
authors = ["vincent@ephais.eu"]
edition = "2021"
description = "Error management library for all the Ephais rust project"
license = "For the exclusive use of Ephais. Reserved Rights."

[dependencies]
